from django.db import models
class profile_data(models.Model):
    first_name = models.CharField(max_length=500)
    last_name  = models.CharField(max_length=500)
    phone =  models.CharField(max_length=500)
    address =  models.CharField(max_length=500)
    email = models.CharField(max_length=500)
    shipping_address_1 = models.CharField(max_length=1000,default="none")
    shipping_address_2 = models.CharField(max_length=1000,default="none")
    shipping_address_3 = models.CharField(max_length=1000,default="none")
    default_shipping_address = models.CharField(max_length=1000,default="none")

class order_cart(models.Model):
    shipping_address = models.CharField(max_length=1000,default="none")
    payment_mode = models.CharField(max_length=500,default="UPI")
    order_id = models.CharField(max_length=500,default="none")
    status = models.CharField(max_length=500,default="none")
    tracking = models.CharField(max_length=500,default="none")
    img = models.ImageField(upload_to = "image",default="none")
    item_name = models.CharField(max_length=1000,default="none")
    item_type = models.CharField(max_length = 1000,default="none")
    category = models.CharField(max_length=1000,default="none")
    link = models.CharField(max_length=1000,default="none")
    item_des = models.CharField(max_length=1000,default="none")
    quantity = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)
    payment_id = models.IntegerField(default=0)
    item_price = models.IntegerField(default=0)
    user = models.CharField(max_length=1000,default="none")
    offer = models.BooleanField(default=False)
    top_add = models.BooleanField(default=False)
    our_special = models.BooleanField(default=False)

class wishlist(models.Model):
    img = models.ImageField(upload_to = "image")
    item_name = models.CharField(max_length=1000)
    item_type = models.CharField(max_length = 1000)
    category = models.CharField(max_length=1000)
    link = models.CharField(max_length=1000)
    item_price = models.IntegerField()
    item_des = models.CharField(max_length=1000)
    offer = models.BooleanField(default=False)
    top_add = models.BooleanField(default=False)
    our_special = models.BooleanField(default=False)
    like = models.CharField(max_length=1000)
    user = models.CharField(max_length=1000,default="none")

