# Generated by Django 4.1.2 on 2023-01-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_data',
            old_name='default_shipping',
            new_name='default_shipping_address',
        ),
    ]
