# Generated by Django 4.1.2 on 2023-01-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_default_shipping_profile_data_default_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_data',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='phone',
            field=models.CharField(max_length=500),
        ),
    ]
