# Generated by Django 4.1.2 on 2023-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_data_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_data',
            name='default_shipping_address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='shipping_address_1',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='shipping_address_2',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='shipping_address_3',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
