# Generated by Django 4.1.2 on 2023-01-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_data_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_data',
        ),
    ]
