# Generated by Django 4.1.2 on 2023-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_delete_profile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('shipping_address_1', models.CharField(default='none', max_length=1000)),
                ('shipping_address_2', models.CharField(default='none', max_length=1000)),
                ('shipping_address_3', models.CharField(default='none', max_length=1000)),
                ('default_shipping_address', models.CharField(default='none', max_length=1000)),
            ],
        ),
    ]
