# Generated by Django 4.1.2 on 2023-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(default='none', max_length=1000)),
                ('payment_mode', models.CharField(max_length=500)),
                ('total_price', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('tracking', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='image')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_type', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_des', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('user', models.CharField(default='none', max_length=1000)),
            ],
        ),
    ]
