# Generated by Django 4.1.2 on 2023-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='category',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='img',
            field=models.ImageField(default='none', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='item_des',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='item_name',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='item_type',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='link',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='order_id',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='payment_mode',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='status',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='tracking',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
