# Generated by Django 4.1.2 on 2023-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_order_cart_category_alter_order_cart_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='payment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
