# Generated by Django 4.1.2 on 2023-01-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_order_cart_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='payment_mode',
            field=models.CharField(default='UPI', max_length=500),
        ),
    ]
