# Generated by Django 4.1.2 on 2023-01-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_order_cart_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_cart',
            name='our_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_cart',
            name='top_add',
            field=models.BooleanField(default=False),
        ),
    ]
