# Generated by Django 4.1.2 on 2023-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_cart_offer_order_cart_our_special_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(default='none', max_length=1000)),
                ('payment_mode', models.CharField(default='UPI', max_length=500)),
                ('order_id', models.CharField(default='none', max_length=500)),
                ('status', models.CharField(default='none', max_length=500)),
                ('tracking', models.CharField(default='none', max_length=500)),
                ('img', models.ImageField(default='none', upload_to='image')),
                ('item_name', models.CharField(default='none', max_length=1000)),
                ('item_type', models.CharField(default='none', max_length=1000)),
                ('category', models.CharField(default='none', max_length=1000)),
                ('link', models.CharField(default='none', max_length=1000)),
                ('item_des', models.CharField(default='none', max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_id', models.IntegerField(default=0)),
                ('item_price', models.IntegerField(default=0)),
                ('user', models.CharField(default='none', max_length=1000)),
                ('offer', models.BooleanField(default=False)),
                ('top_add', models.BooleanField(default=False)),
                ('our_special', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
            ],
        ),
    ]
