# Generated by Django 4.1.2 on 2023-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='tracking',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='category',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_des',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
