# Generated by Django 4.1.2 on 2023-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='like',
            field=models.CharField(max_length=1000),
        ),
    ]
