# Generated by Django 4.1.2 on 2022-12-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_top_ads_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('item_name', models.CharField(max_length=30)),
                ('item_type', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
