# Generated by Django 4.1.2 on 2022-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='link',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
