# Generated by Django 4.1.2 on 2022-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
