# Generated by Django 4.1.2 on 2022-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_items_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
