# Generated by Django 4.1.2 on 2022-12-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_items_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_des',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
