# Generated by Django 4.1.2 on 2022-12-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_items_item_des_items_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_top_ads',
            name='item_des',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home_top_ads',
            name='item_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home_top_ads',
            name='item_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_special',
            name='item_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_top_ads',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
