# Generated by Django 4.1.2 on 2022-12-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_home_top_ads_item_des_home_top_ads_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_special',
            name='item_des',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='categories',
            name='link',
            field=models.CharField(default='category-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='home_top_ads',
            name='item_des',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home_top_ads',
            name='item_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='home_top_ads',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_des',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='our_special',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='our_special',
            name='item_type',
            field=models.CharField(max_length=100),
        ),
    ]
