# Generated by Django 4.1.2 on 2022-12-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_our_special_item_des_alter_categories_cat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_top_ads',
            name='item_des',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='our_special',
            name='item_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='our_special',
            name='item_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='our_special',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
