# Generated by Django 4.1.2 on 2022-12-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_add_cart_category_add_cart_item_des_add_cart_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home_top_ads',
        ),
        migrations.DeleteModel(
            name='our_special',
        ),
        migrations.AddField(
            model_name='add_cart',
            name='item_type',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_cart',
            name='our_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add_cart',
            name='top_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_type',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='our_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='top_add',
            field=models.BooleanField(default=False),
        ),
    ]
