# Generated by Django 4.1.2 on 2023-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_type', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_des', models.CharField(max_length=1000)),
                ('offer', models.BooleanField(default=False)),
                ('top_add', models.BooleanField(default=False)),
                ('our_special', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default='1')),
                ('user', models.CharField(default='none', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='user',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
