# Generated by Django 4.1.2 on 2023-01-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_temp_cart_alter_add_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='add_cart',
            name='our_special',
        ),
        migrations.RemoveField(
            model_name='add_cart',
            name='top_add',
        ),
        migrations.RemoveField(
            model_name='temp_cart',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='temp_cart',
            name='our_special',
        ),
        migrations.RemoveField(
            model_name='temp_cart',
            name='top_add',
        ),
    ]
